on: [push, workflow_dispatch]
name: Build Image
jobs:
  build-image:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
            fetch-depth: 0
      - name: Clone Kuroko
        uses: actions/checkout@v2
        with:
          repository: kuroko-lang/kuroko
          path: kuroko
      - name: Pull Builder Image
        run: docker pull toaruos/build-tools:1.99.x
      - name: Run Builder
        run: docker run -v ${GITHUB_WORKSPACE}:/root/misaka -w /root/misaka -e LANG=C.UTF-8 -t toaruos/build-tools:1.99.x util/build-in-docker.sh
      - name: Upload Branch Image
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            ramdisk.tar
            misaka-kernel
